'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by SpecFlow (http://www.specflow.org/).
'     SpecFlow Version:1.9.0.77
'     SpecFlow Generator Version:1.9.0.0
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
#Region "Designer generated code"
'#pragma warning disable
Imports TechTalk.SpecFlow

Namespace Spr.CricketTicker.SpecTests.Features.CricketTicker
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77"),  _
     System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     NUnit.Framework.TestFixtureAttribute(),  _
     NUnit.Framework.DescriptionAttribute("OneDayMatchSummary"),  _
     NUnit.Framework.CategoryAttribute("ODI")>  _
    Partial Public Class OneDayMatchSummaryFeature
        
        Private Shared testRunner As TechTalk.SpecFlow.ITestRunner
        
#ExternalSource("OneDayMatchSummary.feature",1)
#End ExternalSource
        
        <NUnit.Framework.TestFixtureSetUpAttribute()>  _
        Public Overridable Sub FeatureSetup()
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner
            Dim featureInfo As TechTalk.SpecFlow.FeatureInfo = New TechTalk.SpecFlow.FeatureInfo(New System.Globalization.CultureInfo("en-US"), "OneDayMatchSummary", "In order to..."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"As a..."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"I want to...", ProgrammingLanguage.VB, New String() {"ODI"})
            testRunner.OnFeatureStart(featureInfo)
        End Sub
        
        <NUnit.Framework.TestFixtureTearDownAttribute()>  _
        Public Overridable Sub FeatureTearDown()
            testRunner.OnFeatureEnd
            testRunner = Nothing
        End Sub
        
        <NUnit.Framework.SetUpAttribute()>  _
        Public Overridable Sub TestInitialize()
        End Sub
        
        <NUnit.Framework.TearDownAttribute()>  _
        Public Overridable Sub ScenarioTearDown()
            testRunner.OnScenarioEnd
        End Sub
        
        Public Overridable Sub ScenarioSetup(ByVal scenarioInfo As TechTalk.SpecFlow.ScenarioInfo)
            testRunner.OnScenarioStart(scenarioInfo)
        End Sub
        
        Public Overridable Sub ScenarioCleanup()
            testRunner.CollectScenarioErrors
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Match yet to begin")>  _
        Public Overridable Sub MatchYetToBegin()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Match yet to begin", CType(Nothing,String()))
#ExternalSource("OneDayMatchSummary.feature",7)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",8)
 testRunner.Given("a live One Day match", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",9)
 testRunner.And("the series title is ""5 ODI Cricket Series""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",10)
 testRunner.And("this match is the ""5th ODI"" in the series", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",11)
 testRunner.And("the venue is ""Trent Bridge, Nottingham, England""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",12)
 testRunner.And("the match starts on ""2012-09-05""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",13)
 testRunner.And("the match ends on ""2012-09-05""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
            Dim table1 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Id", "Abbreviation", "Name"})
            table1.AddRow(New String() {"1", "ENG", "England"})
            table1.AddRow(New String() {"2", "PAK", "Pakistan"})
#ExternalSource("OneDayMatchSummary.feature",14)
 testRunner.And("the teams are", CType(Nothing,String), table1, "And ")
#End ExternalSource
            Dim table2 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"InningsNumber", "BattingTeamId", "RunsScored", "WicketsTaken", "Overs", "Run Rate", "Req Run Rate"})
            table2.AddRow(New String() {"1", "1", "0", "0", "0", "0", "0"})
#ExternalSource("OneDayMatchSummary.feature",18)
 testRunner.And("the innings scores are", CType(Nothing,String), table2, "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",21)
 testRunner.And("the status of the match is ""Match yet to begin""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",22)
 testRunner.When("the cricket ticker is updated", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",23)
 testRunner.Then("the match summary should display", "England (ENG) v Pakistan (PAK)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"5 ODI Cricket Series"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"5th ODI (05/09/2012)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Tre"& _ 
                    "nt Bridge, Nottingham, England"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Match yet to begin", CType(Nothing,TechTalk.SpecFlow.Table), "Then ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Match ended with winner")>  _
        Public Overridable Sub MatchEndedWithWinner()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Match ended with winner", CType(Nothing,String()))
#ExternalSource("OneDayMatchSummary.feature",34)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",35)
 testRunner.Given("a live One Day match", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",36)
 testRunner.And("the series title is ""5 ODI Cricket Series""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",37)
 testRunner.And("this match is the ""5th ODI"" in the series", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",38)
 testRunner.And("the venue is ""Trent Bridge, Nottingham, England""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",39)
 testRunner.And("the match starts on ""2012-09-05""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",40)
 testRunner.And("the match ends on ""2012-09-05""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
            Dim table3 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Id", "Abbreviation", "Name"})
            table3.AddRow(New String() {"1", "ENG", "England"})
            table3.AddRow(New String() {"2", "PAK", "Pakistan"})
#ExternalSource("OneDayMatchSummary.feature",41)
 testRunner.And("the teams are", CType(Nothing,String), table3, "And ")
#End ExternalSource
            Dim table4 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"InningsNumber", "BattingTeamId", "RunsScored", "WicketsTaken", "Overs", "Run Rate", "Req Run Rate"})
            table4.AddRow(New String() {"1", "1", "182", "10", "45.2", "4.01", "0"})
            table4.AddRow(New String() {"2", "2", "186", "3", "34.3", "5.39", "0"})
#ExternalSource("OneDayMatchSummary.feature",45)
 testRunner.And("the innings scores are", CType(Nothing,String), table4, "And ")
#End ExternalSource
            Dim table5 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"CurrentInnings", "Day", "Status", "ResultCode"})
            table5.AddRow(New String() {"2", "1", "Match Ended", "Result"})
#ExternalSource("OneDayMatchSummary.feature",49)
 testRunner.And("the match status is", CType(Nothing,String), table5, "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",52)
 testRunner.And("the winning team Id is 2", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",53)
 testRunner.When("the cricket ticker is updated", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",54)
 testRunner.Then("the match summary should display", "England (ENG) v Pakistan (PAK)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"5 ODI Cricket Series"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"5th ODI (05/09/2012)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Tre"& _ 
                    "nt Bridge, Nottingham, England"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Match Ended"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"PAK win", CType(Nothing,TechTalk.SpecFlow.Table), "Then ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Unable to take ten wickets in first innings")>  _
        Public Overridable Sub UnableToTakeTenWicketsInFirstInnings()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Unable to take ten wickets in first innings", CType(Nothing,String()))
#ExternalSource("OneDayMatchSummary.feature",66)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",67)
 testRunner.Given("a live One Day match", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",68)
 testRunner.And("the series title is ""5 ODI Cricket Series""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",69)
 testRunner.And("this match is the ""2nd ODI"" in the series", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",70)
 testRunner.And("the venue is ""The Rose Bowl, Southampton, England""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",71)
 testRunner.And("the match starts on ""2012-08-28""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",72)
 testRunner.And("the match ends on ""2012-08-28""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
            Dim table6 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Id", "Abbreviation", "Name"})
            table6.AddRow(New String() {"1", "ENG", "England"})
            table6.AddRow(New String() {"2", "SA", "South Africa"})
#ExternalSource("OneDayMatchSummary.feature",73)
 testRunner.And("the teams are", CType(Nothing,String), table6, "And ")
#End ExternalSource
            Dim table7 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"InningsNumber", "BattingTeamId", "RunsScored", "WicketsTaken", "Overs", "Run Rate", "Req Run Rate"})
            table7.AddRow(New String() {"1", "2", "287", "5", "50", "5.74", "0"})
            table7.AddRow(New String() {"2", "1", "152", "5", "32", "4.75", "7.55"})
#ExternalSource("OneDayMatchSummary.feature",77)
 testRunner.And("the innings scores are", CType(Nothing,String), table7, "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",81)
 testRunner.And("the status of the match is ""Drinks""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",82)
 testRunner.When("the cricket ticker is updated", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",83)
 testRunner.Then("the match summary should display", "England (ENG) v South Africa (SA)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"5 ODI Cricket Series"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2nd ODI (28/08/2012)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)& _ 
                    "The Rose Bowl, Southampton, England"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Drinks"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"ENG trail by 135 runs after 32 ov"& _ 
                    "ers."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Required run rate is 7.6", CType(Nothing,TechTalk.SpecFlow.Table), "Then ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Seconds innings in progress")>  _
        Public Overridable Sub SecondsInningsInProgress()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Seconds innings in progress", CType(Nothing,String()))
#ExternalSource("OneDayMatchSummary.feature",96)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",97)
 testRunner.Given("a live One Day match", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",98)
 testRunner.And("the series title is ""3 ODI Cricket Series in United Arab Emirates""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",99)
 testRunner.And("this match is the ""1st ODI"" in the series", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",100)
 testRunner.And("the venue is ""Sharjah Cricket Association Stadium, Sharjah, United Arab Emirates"""& _ 
                    "", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",101)
 testRunner.And("the match starts on ""2012-08-28""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",102)
 testRunner.And("the match ends on ""2012-08-28""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
            Dim table8 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Id", "Abbreviation", "Name"})
            table8.AddRow(New String() {"1", "PAK", "Pakistan"})
            table8.AddRow(New String() {"2", "AUS", "Australia"})
#ExternalSource("OneDayMatchSummary.feature",103)
 testRunner.And("the teams are", CType(Nothing,String), table8, "And ")
#End ExternalSource
            Dim table9 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"InningsNumber", "BattingTeamId", "RunsScored", "WicketsTaken", "Overs", "Run Rate", "Req Run Rate"})
            table9.AddRow(New String() {"1", "1", "198", "10", "45.1", "4.38", "0"})
            table9.AddRow(New String() {"2", "2", "21", "1", "5", "4.2", "3.95"})
#ExternalSource("OneDayMatchSummary.feature",107)
 testRunner.And("the innings scores are", CType(Nothing,String), table9, "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",111)
 testRunner.And("the status of the match is ""Play in Progress""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",112)
 testRunner.When("the cricket ticker is updated", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",113)
 testRunner.Then("the match summary should display", "Pakistan (PAK) v Australia (AUS)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"3 ODI Cricket Series in United Arab Emirates"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"1st ODI (28/08/2012)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Sharjah Cricket Association Stadium, Sharjah, United Arab"& _ 
                    " Emirates"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Play in Progress"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"AUS trail by 177 runs after 5 overs."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Required ru"& _ 
                    "n rate is 4.0", CType(Nothing,TechTalk.SpecFlow.Table), "Then ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("First innings in progress")>  _
        Public Overridable Sub FirstInningsInProgress()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("First innings in progress", CType(Nothing,String()))
#ExternalSource("OneDayMatchSummary.feature",126)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",127)
 testRunner.Given("a live One Day match", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",128)
 testRunner.And("the series title is ""3 T20 Cricket Series in United Arab Emirates""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",129)
 testRunner.And("this match is the ""3rd T20I"" in the series", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",130)
 testRunner.And("the venue is ""Dubai International Cricket Stadium, Dubai, United Arab Emirates""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",131)
 testRunner.And("the match starts on ""2012-09-10""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",132)
 testRunner.And("the match ends on ""2012-09-10""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
            Dim table10 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Id", "Abbreviation", "Name"})
            table10.AddRow(New String() {"1", "PAK", "Pakistan"})
            table10.AddRow(New String() {"2", "AUS", "Australia"})
#ExternalSource("OneDayMatchSummary.feature",133)
 testRunner.And("the teams are", CType(Nothing,String), table10, "And ")
#End ExternalSource
            Dim table11 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"InningsNumber", "BattingTeamId", "RunsScored", "WicketsTaken", "Overs", "Run Rate", "Req Run Rate"})
            table11.AddRow(New String() {"1", "2", "47", "0", "6.4", "7.0", "0"})
#ExternalSource("OneDayMatchSummary.feature",137)
 testRunner.And("the innings scores are", CType(Nothing,String), table11, "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",140)
 testRunner.And("the status of the match is ""Play in Progress""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",141)
 testRunner.When("the cricket ticker is updated", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
#ExternalSource("OneDayMatchSummary.feature",142)
 testRunner.Then("the match summary should display", "Pakistan (PAK) v Australia (AUS)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"3 T20 Cricket Series in United Arab Emirates"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"3rd T20I (10/09/2012)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Dubai International Cricket Stadium, Dubai, United Arab "& _ 
                    "Emirates"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Play in Progress", CType(Nothing,TechTalk.SpecFlow.Table), "Then ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
    End Class
End Namespace
'#pragma warning restore
#End Region
