'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by SpecFlow (http://www.specflow.org/).
'     SpecFlow Version:1.9.0.77
'     SpecFlow Generator Version:1.9.0.0
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
#Region "Designer generated code"
'#pragma warning disable
Imports TechTalk.SpecFlow

Namespace Spr.CricketTicker.SpecTests.Features.CricketTicker
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77"),  _
     System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     NUnit.Framework.TestFixtureAttribute(),  _
     NUnit.Framework.DescriptionAttribute("TestMatchSummary"),  _
     NUnit.Framework.CategoryAttribute("TestMatch")>  _
    Partial Public Class TestMatchSummaryFeature
        
        Private Shared testRunner As TechTalk.SpecFlow.ITestRunner
        
#ExternalSource("TestMatchSummary.feature",1)
#End ExternalSource
        
        <NUnit.Framework.TestFixtureSetUpAttribute()>  _
        Public Overridable Sub FeatureSetup()
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner
            Dim featureInfo As TechTalk.SpecFlow.FeatureInfo = New TechTalk.SpecFlow.FeatureInfo(New System.Globalization.CultureInfo("en-US"), "TestMatchSummary", "", ProgrammingLanguage.VB, New String() {"TestMatch"})
            testRunner.OnFeatureStart(featureInfo)
        End Sub
        
        <NUnit.Framework.TestFixtureTearDownAttribute()>  _
        Public Overridable Sub FeatureTearDown()
            testRunner.OnFeatureEnd
            testRunner = Nothing
        End Sub
        
        <NUnit.Framework.SetUpAttribute()>  _
        Public Overridable Sub TestInitialize()
        End Sub
        
        <NUnit.Framework.TearDownAttribute()>  _
        Public Overridable Sub ScenarioTearDown()
            testRunner.OnScenarioEnd
        End Sub
        
        Public Overridable Sub ScenarioSetup(ByVal scenarioInfo As TechTalk.SpecFlow.ScenarioInfo)
            testRunner.OnScenarioStart(scenarioInfo)
        End Sub
        
        Public Overridable Sub ScenarioCleanup()
            testRunner.CollectScenarioErrors
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Match yet to begin")>  _
        Public Overridable Sub MatchYetToBegin()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Match yet to begin", CType(Nothing,String()))
#ExternalSource("TestMatchSummary.feature",4)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",5)
 testRunner.Given("a live Test match", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",6)
 testRunner.And("the series title is ""3 Test Cricket Series""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",7)
 testRunner.And("this match is the ""2nd Test"" in the series", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",8)
 testRunner.And("the venue is ""Newlands, Cape Town, South Africa""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",9)
 testRunner.And("the match starts on ""2013-02-14""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",10)
 testRunner.And("the match ends on ""2013-02-18""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
            Dim table1 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Id", "Abbreviation", "Name"})
            table1.AddRow(New String() {"1", "SA", "South Africa"})
            table1.AddRow(New String() {"2", "PAK", "Pakistan"})
#ExternalSource("TestMatchSummary.feature",11)
 testRunner.And("the teams are", CType(Nothing,String), table1, "And ")
#End ExternalSource
            Dim table2 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"InningsNumber", "BattingTeamId", "RunsScored", "WicketsTaken"})
            table2.AddRow(New String() {"1", "1", "0", "0"})
#ExternalSource("TestMatchSummary.feature",15)
 testRunner.And("the innings scores are", CType(Nothing,String), table2, "And ")
#End ExternalSource
            Dim table3 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"CurrentInnings", "Day", "Status", "ResultCode"})
            table3.AddRow(New String() {"1", "1", "Match yet to begin", "None"})
#ExternalSource("TestMatchSummary.feature",18)
 testRunner.And("the match status is", CType(Nothing,String), table3, "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",21)
 testRunner.When("the cricket ticker is updated", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",22)
 testRunner.Then("the match summary should display", "South Africa (SA) v Pakistan (PAK)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"3 Test Cricket Series"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2nd Test (14/02/2013"& _ 
                    " - 18/02/2013)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Newlands, Cape Town, South Africa"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Day 1: Match yet to begin", CType(Nothing,TechTalk.SpecFlow.Table), "Then ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Match abandoned")>  _
        Public Overridable Sub MatchAbandoned()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Match abandoned", CType(Nothing,String()))
#ExternalSource("TestMatchSummary.feature",33)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",34)
 testRunner.Given("a live Test match", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",35)
 testRunner.And("the series title is ""2 Test Cricket Series""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",36)
 testRunner.And("this match is the ""2nd Test"" in the series", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",37)
 testRunner.And("the venue is ""St George's Park, Port Elizabeth, South Africa""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",38)
 testRunner.And("the match starts on ""2013-01-11""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",39)
 testRunner.And("the match ends on ""2013-01-15""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
            Dim table4 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Id", "Abbreviation", "Name"})
            table4.AddRow(New String() {"1", "SA", "South Africa"})
            table4.AddRow(New String() {"2", "NZ", "New Zealand"})
#ExternalSource("TestMatchSummary.feature",40)
 testRunner.And("the teams are", CType(Nothing,String), table4, "And ")
#End ExternalSource
            Dim table5 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"InningsNumber", "BattingTeamId", "RunsScored", "WicketsTaken"})
            table5.AddRow(New String() {"1", "1", "525", "8"})
            table5.AddRow(New String() {"2", "2", "121", "10"})
            table5.AddRow(New String() {"3", "2", "257", "10"})
#ExternalSource("TestMatchSummary.feature",44)
 testRunner.And("the innings scores are", CType(Nothing,String), table5, "And ")
#End ExternalSource
            Dim table6 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"CurrentInnings", "Day", "Status", "ResultCode"})
            table6.AddRow(New String() {"3", "4", "Match Ended", "Abandoned"})
#ExternalSource("TestMatchSummary.feature",49)
 testRunner.And("the match status is", CType(Nothing,String), table6, "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",52)
 testRunner.When("the cricket ticker is updated", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",53)
 testRunner.Then("the match summary should display", "South Africa (SA) v New Zealand (NZ)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2 Test Cricket Series"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2nd Test (11/01/20"& _ 
                    "13 - 15/01/2013)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"St George's Park, Port Elizabeth, South Africa"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Day 4: Match"& _ 
                    " Abandoned", CType(Nothing,TechTalk.SpecFlow.Table), "Then ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("We have a winner")>  _
        Public Overridable Sub WeHaveAWinner()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("We have a winner", CType(Nothing,String()))
#ExternalSource("TestMatchSummary.feature",64)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",65)
 testRunner.Given("a live Test match", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",66)
 testRunner.And("the series title is ""2 Test Cricket Series""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",67)
 testRunner.And("this match is the ""2nd Test"" in the series", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",68)
 testRunner.And("the venue is ""St George's Park, Port Elizabeth, South Africa""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",69)
 testRunner.And("the match starts on ""2013-01-11""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",70)
 testRunner.And("the match ends on ""2013-01-15""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
            Dim table7 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Id", "Abbreviation", "Name"})
            table7.AddRow(New String() {"1", "SA", "South Africa"})
            table7.AddRow(New String() {"2", "NZ", "New Zealand"})
#ExternalSource("TestMatchSummary.feature",71)
 testRunner.And("the teams are", CType(Nothing,String), table7, "And ")
#End ExternalSource
            Dim table8 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"InningsNumber", "BattingTeamId", "RunsScored", "WicketsTaken"})
            table8.AddRow(New String() {"1", "1", "525", "8"})
            table8.AddRow(New String() {"2", "2", "121", "10"})
            table8.AddRow(New String() {"3", "2", "257", "10"})
#ExternalSource("TestMatchSummary.feature",75)
 testRunner.And("the innings scores are", CType(Nothing,String), table8, "And ")
#End ExternalSource
            Dim table9 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"CurrentInnings", "Day", "Status", "ResultCode"})
            table9.AddRow(New String() {"3", "4", "Match Ended", "Result"})
#ExternalSource("TestMatchSummary.feature",80)
 testRunner.And("the match status is", CType(Nothing,String), table9, "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",83)
 testRunner.And("the winning team Id is 1", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",84)
 testRunner.When("the cricket ticker is updated", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",85)
 testRunner.Then("the match summary should display", "South Africa (SA) v New Zealand (NZ)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2 Test Cricket Series"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2nd Test (11/01/20"& _ 
                    "13 - 15/01/2013)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"St George's Park, Port Elizabeth, South Africa"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Day 4: Match"& _ 
                    " Ended"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SA win", CType(Nothing,TechTalk.SpecFlow.Table), "Then ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Start of first innings no score")>  _
        Public Overridable Sub StartOfFirstInningsNoScore()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Start of first innings no score", CType(Nothing,String()))
#ExternalSource("TestMatchSummary.feature",97)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",98)
 testRunner.Given("a live Test match", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",99)
 testRunner.And("the series title is ""2 Test Cricket Series""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",100)
 testRunner.And("this match is the ""1st Test"" in the series", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",101)
 testRunner.And("the venue is ""Rajiv Gandhi International Stadium, Hyderabad, India""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",102)
 testRunner.And("the match starts on ""2012-08-23""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",103)
 testRunner.And("the match ends on ""2012-08-27""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
            Dim table10 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Id", "Abbreviation", "Name"})
            table10.AddRow(New String() {"1", "IND", "India"})
            table10.AddRow(New String() {"2", "NZ", "New Zealand"})
#ExternalSource("TestMatchSummary.feature",104)
 testRunner.And("the teams are", CType(Nothing,String), table10, "And ")
#End ExternalSource
            Dim table11 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"InningsNumber", "BattingTeamId", "RunsScored", "WicketsTaken"})
            table11.AddRow(New String() {"1", "1", "0", "0"})
#ExternalSource("TestMatchSummary.feature",108)
 testRunner.And("the innings scores are", CType(Nothing,String), table11, "And ")
#End ExternalSource
            Dim table12 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"CurrentInnings", "Day", "Status", "ResultCode"})
            table12.AddRow(New String() {"1", "1", "Not Started", "None"})
#ExternalSource("TestMatchSummary.feature",111)
 testRunner.And("the match status is", CType(Nothing,String), table12, "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",114)
 testRunner.When("the cricket ticker is updated", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",115)
 testRunner.Then("the match summary should display", "India (IND) v New Zealand (NZ)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2 Test Cricket Series"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"1st Test (23/08/2012 - 2"& _ 
                    "7/08/2012)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Rajiv Gandhi International Stadium, Hyderabad, India"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Day 1: Not S"& _ 
                    "tarted"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Innings #1", CType(Nothing,TechTalk.SpecFlow.Table), "Then ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("In progress on day two")>  _
        Public Overridable Sub InProgressOnDayTwo()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("In progress on day two", CType(Nothing,String()))
#ExternalSource("TestMatchSummary.feature",127)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",128)
 testRunner.Given("a live Test match", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",129)
 testRunner.And("the series title is ""2 Test Cricket Series""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",130)
 testRunner.And("this match is the ""1st Test"" in the series", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",131)
 testRunner.And("the venue is ""Rajiv Gandhi International Stadium, Hyderabad, India""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",132)
 testRunner.And("the match starts on ""2012-08-23""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",133)
 testRunner.And("the match ends on ""2012-08-27""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
            Dim table13 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Id", "Abbreviation", "Name"})
            table13.AddRow(New String() {"1", "IND", "India"})
            table13.AddRow(New String() {"2", "NZ", "New Zealand"})
#ExternalSource("TestMatchSummary.feature",134)
 testRunner.And("the teams are", CType(Nothing,String), table13, "And ")
#End ExternalSource
            Dim table14 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"InningsNumber", "BattingTeamId", "RunsScored", "WicketsTaken"})
            table14.AddRow(New String() {"1", "1", "438", "10"})
            table14.AddRow(New String() {"2", "2", "35", "2"})
#ExternalSource("TestMatchSummary.feature",138)
 testRunner.And("the innings scores are", CType(Nothing,String), table14, "And ")
#End ExternalSource
            Dim table15 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"CurrentInnings", "Day", "Status", "ResultCode"})
            table15.AddRow(New String() {"2", "2", "In Progress", "None"})
#ExternalSource("TestMatchSummary.feature",142)
 testRunner.And("the match status is", CType(Nothing,String), table15, "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",145)
 testRunner.When("the cricket ticker is updated", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",146)
 testRunner.Then("the match summary should display", "India (IND) v New Zealand (NZ)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2 Test Cricket Series"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"1st Test (23/08/2012 - 2"& _ 
                    "7/08/2012)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Rajiv Gandhi International Stadium, Hyderabad, India"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Day 2: In Pr"& _ 
                    "ogress"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Innings #2"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"NZ trail by 403 runs", CType(Nothing,TechTalk.SpecFlow.Table), "Then ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Stumps on day three")>  _
        Public Overridable Sub StumpsOnDayThree()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Stumps on day three", CType(Nothing,String()))
#ExternalSource("TestMatchSummary.feature",159)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",160)
 testRunner.Given("a live Test match", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",161)
 testRunner.And("the series title is ""2 Test Cricket Series""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",162)
 testRunner.And("this match is the ""2nd Test"" in the series", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",163)
 testRunner.And("the venue is ""St George's Park, Port Elizabeth, South Africa""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",164)
 testRunner.And("the match starts on ""2013-01-11""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",165)
 testRunner.And("the match ends on ""2013-01-15""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
            Dim table16 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Id", "Abbreviation", "Name"})
            table16.AddRow(New String() {"1", "SA", "South Africa"})
            table16.AddRow(New String() {"2", "NZ", "New Zealand"})
#ExternalSource("TestMatchSummary.feature",166)
 testRunner.And("the teams are", CType(Nothing,String), table16, "And ")
#End ExternalSource
            Dim table17 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"InningsNumber", "BattingTeamId", "RunsScored", "WicketsTaken"})
            table17.AddRow(New String() {"1", "1", "525", "8"})
            table17.AddRow(New String() {"2", "2", "121", "10"})
            table17.AddRow(New String() {"3", "2", "157", "4"})
#ExternalSource("TestMatchSummary.feature",170)
 testRunner.And("the innings scores are", CType(Nothing,String), table17, "And ")
#End ExternalSource
            Dim table18 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"CurrentInnings", "Day", "Status", "ResultCode"})
            table18.AddRow(New String() {"3", "3", "Stumps", "None"})
#ExternalSource("TestMatchSummary.feature",175)
 testRunner.And("the match status is", CType(Nothing,String), table18, "And ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",178)
 testRunner.When("the cricket ticker is updated", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
#ExternalSource("TestMatchSummary.feature",179)
 testRunner.Then("the match summary should display", "South Africa (SA) v New Zealand (NZ)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2 Test Cricket Series"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2nd Test (11/01/20"& _ 
                    "13 - 15/01/2013)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"St George's Park, Port Elizabeth, South Africa"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Day 3: Stump"& _ 
                    "s"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Innings #3"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"NZ trail by 247 runs", CType(Nothing,TechTalk.SpecFlow.Table), "Then ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
    End Class
End Namespace
'#pragma warning restore
#End Region
