'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by SpecFlow (http://www.specflow.org/).
'     SpecFlow Version:1.9.0.77
'     SpecFlow Generator Version:1.9.0.0
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
#Region "Designer generated code"
'#pragma warning disable
Imports TechTalk.SpecFlow

Namespace Spr.CricketTicker.SpecTests.Features.GameSelector
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77"),  _
     System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     NUnit.Framework.TestFixtureAttribute(),  _
     NUnit.Framework.DescriptionAttribute("Game Selector")>  _
    Partial Public Class GameSelectorFeature
        
        Private Shared testRunner As TechTalk.SpecFlow.ITestRunner
        
#ExternalSource("GameSelector.feature",1)
#End ExternalSource
        
        <NUnit.Framework.TestFixtureSetUpAttribute()>  _
        Public Overridable Sub FeatureSetup()
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner
            Dim featureInfo As TechTalk.SpecFlow.FeatureInfo = New TechTalk.SpecFlow.FeatureInfo(New System.Globalization.CultureInfo("en-US"), "Game Selector", "In order to keep up-to-date on the cricket"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"As a cricket fan"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"I want to select fr"& _ 
                    "om a list of available games", ProgrammingLanguage.VB, CType(Nothing,String()))
            testRunner.OnFeatureStart(featureInfo)
        End Sub
        
        <NUnit.Framework.TestFixtureTearDownAttribute()>  _
        Public Overridable Sub FeatureTearDown()
            testRunner.OnFeatureEnd
            testRunner = Nothing
        End Sub
        
        <NUnit.Framework.SetUpAttribute()>  _
        Public Overridable Sub TestInitialize()
        End Sub
        
        <NUnit.Framework.TearDownAttribute()>  _
        Public Overridable Sub ScenarioTearDown()
            testRunner.OnScenarioEnd
        End Sub
        
        Public Overridable Sub ScenarioSetup(ByVal scenarioInfo As TechTalk.SpecFlow.ScenarioInfo)
            testRunner.OnScenarioStart(scenarioInfo)
        End Sub
        
        Public Overridable Sub ScenarioCleanup()
            testRunner.CollectScenarioErrors
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Double clicking upcoming game with no sub title")>  _
        Public Overridable Sub DoubleClickingUpcomingGameWithNoSubTitle()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Double clicking upcoming game with no sub title", CType(Nothing,String()))
#ExternalSource("GameSelector.feature",6)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("GameSelector.feature",7)
 testRunner.Given("the sample upcoming games feed ""UpcomingIncludingThreeWorldCup""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("GameSelector.feature",8)
 testRunner.And("the current date is ""2012-09-15""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("GameSelector.feature",9)
 testRunner.When("the game selector starts", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
            Dim table1 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Game", "Status", "Game Id"})
            table1.AddRow(New String() {"Bangladesh v Zimbabwe, Match 5", "05:00", "184572"})
#ExternalSource("GameSelector.feature",10)
 testRunner.Then("the game selector should display the following entries", CType(Nothing,String), table1, "Then ")
#End ExternalSource
#ExternalSource("GameSelector.feature",13)
 testRunner.When("I double click on the upcoming game with Id equal to ""184572""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
#ExternalSource("GameSelector.feature",14)
 testRunner.Then("display the following additional game information", "ICC World Twenty20 Warm-up Matches"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2012"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Match 5"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Colts Cricket Club Ground, C"& _ 
                    "olombo", CType(Nothing,TechTalk.SpecFlow.Table), "Then ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Double clicking upcoming game shows more details")>  _
        Public Overridable Sub DoubleClickingUpcomingGameShowsMoreDetails()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Double clicking upcoming game shows more details", CType(Nothing,String()))
#ExternalSource("GameSelector.feature",23)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("GameSelector.feature",24)
 testRunner.Given("the sample upcoming games feed ""UpcomingFourOdiOneTest""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("GameSelector.feature",25)
 testRunner.And("the current date is ""2012-08-30""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("GameSelector.feature",26)
 testRunner.When("the game selector starts", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
            Dim table2 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Game", "Status", "Game Id"})
            table2.AddRow(New String() {"India v New Zealand, 2nd Test", "31/08/2012 05:00", "108609"})
            table2.AddRow(New String() {"England v South Africa, 3rd ODI", "31/08/2012 13:00", "104903"})
            table2.AddRow(New String() {"Pakistan v Australia, 2nd ODI", "31/08/2012 15:00", "184299"})
#ExternalSource("GameSelector.feature",27)
 testRunner.Then("the game selector should display the following entries", CType(Nothing,String), table2, "Then ")
#End ExternalSource
#ExternalSource("GameSelector.feature",32)
 testRunner.When("I double click on the upcoming game with Id equal to ""108609""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
#ExternalSource("GameSelector.feature",33)
 testRunner.Then("display the following additional game information", "New Zealand in India Test Series"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2 Test Cricket Series, 2012"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2nd Test"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"M.Chin"& _ 
                    "naswamy Stadium, Bengaluru", CType(Nothing,TechTalk.SpecFlow.Table), "Then ")
#End ExternalSource
#ExternalSource("GameSelector.feature",41)
 testRunner.When("I double click on the upcoming game with Id equal to ""184299""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
#ExternalSource("GameSelector.feature",42)
 testRunner.Then("display the following additional game information", "Australia vs Pakistan ODI Series"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"3 ODI Cricket Series in United Arab Emirates, 2"& _ 
                    "012"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2nd ODI"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Sheikh Zayed Stadium, Abu Dhabi", CType(Nothing,TechTalk.SpecFlow.Table), "Then ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Double click live game should launch ticker")>  _
        Public Overridable Sub DoubleClickLiveGameShouldLaunchTicker()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Double click live game should launch ticker", CType(Nothing,String()))
#ExternalSource("GameSelector.feature",51)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("GameSelector.feature",52)
 testRunner.Given("the sample live games feed ""OneOdiOneTest""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("GameSelector.feature",53)
 testRunner.When("the game selector starts", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
            Dim table3 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Game", "Status", "Game Id"})
            table3.AddRow(New String() {"India v New Zealand, 1st Test", "Play In Progress", "108608"})
            table3.AddRow(New String() {"England v South Africa, 1st ODI", "Rain Stoppage", "104901"})
#ExternalSource("GameSelector.feature",54)
 testRunner.Then("the game selector should display the following entries", CType(Nothing,String), table3, "Then ")
#End ExternalSource
#ExternalSource("GameSelector.feature",58)
 testRunner.When("I double click on the upcoming game with Id equal to ""108608""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
#ExternalSource("GameSelector.feature",59)
 testRunner.Then("a cricket ticker should be launched", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Then ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Runtime error with Upcoming Games feed")>  _
        Public Overridable Sub RuntimeErrorWithUpcomingGamesFeed()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Runtime error with Upcoming Games feed", CType(Nothing,String()))
#ExternalSource("GameSelector.feature",61)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("GameSelector.feature",62)
 testRunner.Given("an unexpected error with the Upcoming Games feed", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("GameSelector.feature",63)
 testRunner.When("the game selector starts", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
            Dim table4 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Game", "Status", "Game Id"})
            table4.AddRow(New String() {"Unexpected problem with the Upcoming Games feed!", "FAILED", ""})
#ExternalSource("GameSelector.feature",64)
 testRunner.Then("the game selector should display the following entries", CType(Nothing,String), table4, "Then ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Runtime error with Live Games feed")>  _
        Public Overridable Sub RuntimeErrorWithLiveGamesFeed()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Runtime error with Live Games feed", CType(Nothing,String()))
#ExternalSource("GameSelector.feature",68)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("GameSelector.feature",69)
 testRunner.Given("an unexpected error with the Live Games feed", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("GameSelector.feature",70)
 testRunner.When("the game selector starts", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
            Dim table5 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Game", "Status", "Game Id"})
            table5.AddRow(New String() {"Unexpected problem with the Live Games feed!", "FAILED", ""})
#ExternalSource("GameSelector.feature",71)
 testRunner.Then("the game selector should display the following entries", CType(Nothing,String), table5, "Then ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("One or more live games available")>  _
        Public Overridable Sub OneOrMoreLiveGamesAvailable()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("One or more live games available", CType(Nothing,String()))
#ExternalSource("GameSelector.feature",75)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("GameSelector.feature",76)
 testRunner.Given("the sample live games feed ""OneOdiOneTest""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("GameSelector.feature",77)
 testRunner.When("the game selector starts", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
            Dim table6 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Game", "Status", "Game Id"})
            table6.AddRow(New String() {"India v New Zealand, 1st Test", "Play In Progress", "108608"})
            table6.AddRow(New String() {"England v South Africa, 1st ODI", "Rain Stoppage", "104901"})
#ExternalSource("GameSelector.feature",78)
 testRunner.Then("the game selector should display the following entries", CType(Nothing,String), table6, "Then ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("No live games")>  _
        Public Overridable Sub NoLiveGames()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("No live games", CType(Nothing,String()))
#ExternalSource("GameSelector.feature",83)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("GameSelector.feature",84)
 testRunner.Given("the sample live games feed ""NoGames""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("GameSelector.feature",85)
 testRunner.When("the game selector starts", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
#ExternalSource("GameSelector.feature",86)
 testRunner.Then("the game selector should display nothing", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Then ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("No upcoming games")>  _
        Public Overridable Sub NoUpcomingGames()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("No upcoming games", CType(Nothing,String()))
#ExternalSource("GameSelector.feature",88)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("GameSelector.feature",89)
 testRunner.Given("the sample upcoming games feed ""UpcomingFourOdiOneTest""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("GameSelector.feature",90)
 testRunner.And("the current date is ""2013-08-01""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("GameSelector.feature",91)
 testRunner.When("the game selector starts", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
#ExternalSource("GameSelector.feature",92)
 testRunner.Then("the game selector should display nothing", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Then ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Upcoming games start after current date")>  _
        Public Overridable Sub UpcomingGamesStartAfterCurrentDate()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Upcoming games start after current date", CType(Nothing,String()))
#ExternalSource("GameSelector.feature",94)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("GameSelector.feature",95)
 testRunner.Given("the sample upcoming games feed ""UpcomingFourOdiOneTest""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("GameSelector.feature",96)
 testRunner.And("the current date is ""2012-08-30""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("GameSelector.feature",97)
 testRunner.When("the game selector starts", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
            Dim table7 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Game", "Status", "Game Id"})
            table7.AddRow(New String() {"India v New Zealand, 2nd Test", "31/08/2012 05:00", "108609"})
            table7.AddRow(New String() {"England v South Africa, 3rd ODI", "31/08/2012 13:00", "104903"})
            table7.AddRow(New String() {"Pakistan v Australia, 2nd ODI", "31/08/2012 15:00", "184299"})
#ExternalSource("GameSelector.feature",98)
 testRunner.Then("the game selector should display the following entries", CType(Nothing,String), table7, "Then ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Upcoming games start on current date")>  _
        Public Overridable Sub UpcomingGamesStartOnCurrentDate()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Upcoming games start on current date", CType(Nothing,String()))
#ExternalSource("GameSelector.feature",104)
Me.ScenarioSetup(scenarioInfo)
#End ExternalSource
#ExternalSource("GameSelector.feature",105)
 testRunner.Given("the sample upcoming games feed ""UpcomingFourOdiOneTest""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("GameSelector.feature",106)
 testRunner.And("the current date is ""2012-08-31""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "And ")
#End ExternalSource
#ExternalSource("GameSelector.feature",107)
 testRunner.When("the game selector starts", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
            Dim table8 As TechTalk.SpecFlow.Table = New TechTalk.SpecFlow.Table(New String() {"Game", "Status", "Game Id"})
            table8.AddRow(New String() {"India v New Zealand, 2nd Test", "05:00", "108609"})
            table8.AddRow(New String() {"England v South Africa, 3rd ODI", "13:00", "104903"})
            table8.AddRow(New String() {"Pakistan v Australia, 2nd ODI", "15:00", "184299"})
#ExternalSource("GameSelector.feature",108)
 testRunner.Then("the game selector should display the following entries", CType(Nothing,String), table8, "Then ")
#End ExternalSource
            Me.ScenarioCleanup
        End Sub
    End Class
End Namespace
'#pragma warning restore
#End Region
